install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt55
  - sudo apt-get update -qq
  - apt-cache search libqt5serialport
  - sudo apt-get install qt55base qt55serialport qt55tools
  - which qmake

script:
  - source /opt/qt55/bin/qt55-env.sh
  - qmake RepRaptor.pro
  - make
