install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt55base qt55serialport qt55tools
  - which qmake

script:
  - source /opt/qt55/bin/qt55-env.sh
  - qmake RepRaptor.pro
  - make
